### ISSUE TITLE
Two Simultaneous Speakers, 7 selections

### ISSUE THREAD

**Issue by egapevets2** [aspage2/Remote#3]
Change speakers to Radio buttons, but you could have two buttons on at once, not three.
You could turn ON fam room and BackYard.  
OFF turns everything off, including the amplifier.
If Two are ON and you click a third, the two already ON turn OFF, and only the third remains ON.
Question - is the AMP a hardware OR of the speaker selections, or do we turn it on independenly?
For some reason, I think I have a hardware circuit that prevents more than two speakers on, because paralleling too many gets you down sub four ohms, which maybe would blow the amp up?

![twospeakers](https://user-images.githubusercontent.com/42898704/44998315-1cde4600-af7a-11e8-9bd2-629accaa33f2.jpg)

**Comment by aspage2** [comment]
[commit](https://github.com/aspage2/Remote/commit/0baa5ea8d600c9012be83a44a20fbd802fc67323)
